3.0.0-svn-229
        * WikiTagBase sometimes tried to getMessage() on a null exception, added an extra check on that.
        
        * JavaDoc fixes
        
        * Error.jsp was is own error page causing endless loops, removed the errorPage tag.
        
        * Error.jsp was using  ${error.realCause.class.name} causing :
           javax.el.ELException: The identifier [class] is not a valid Java identifier as required by 
           section 1.19 of the EL specification (Identifier ::= Java language identifier). 
           This check can be disabled by setting the system property org.apache.el.parser.SKIP_IDENTIFIER_CHECK to true.
           
           An extra getter was added on the MessageActionBean to circumvent this.
           We should now at least get clearer error messages.
        

git-svn-id: https://svn.apache.org/repos/asf/incubator/jspwiki/trunk@1101114 13f79535-47bb-0310-9956-ffa450edef68